# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ecommerce_pb2 as ecommerce__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecommerce_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/ecommerce.CustomerService/Register',
                request_serializer=ecommerce__pb2.RegisterRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/ecommerce.CustomerService/Login',
                request_serializer=ecommerce__pb2.LoginRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.SaveSession = channel.unary_unary(
                '/ecommerce.CustomerService/SaveSession',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/ecommerce.CustomerService/ValidateSession',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/ecommerce.CustomerService/Logout',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUserData = channel.unary_unary(
                '/ecommerce.CustomerService/GetUserData',
                request_serializer=ecommerce__pb2.UserRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateFeedback = channel.unary_unary(
                '/ecommerce.CustomerService/UpdateFeedback',
                request_serializer=ecommerce__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/ecommerce.CustomerService/GetCart',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.CartResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/ecommerce.CustomerService/AddToCart',
                request_serializer=ecommerce__pb2.CartItemRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/ecommerce.CustomerService/RemoveFromCart',
                request_serializer=ecommerce__pb2.CartItemRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/ecommerce.CustomerService/ClearCart',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/ecommerce.CustomerService/SaveCart',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.AddPurchasedItems = channel.unary_unary(
                '/ecommerce.CustomerService/AddPurchasedItems',
                request_serializer=ecommerce__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/ecommerce.CustomerService/PlaceOrder',
                request_serializer=ecommerce__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.GetBuyerOrders = channel.unary_unary(
                '/ecommerce.CustomerService/GetBuyerOrders',
                request_serializer=ecommerce__pb2.UserRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetSellerOrders = channel.unary_unary(
                '/ecommerce.CustomerService/GetSellerOrders',
                request_serializer=ecommerce__pb2.UserRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.UpdateOrderStatus = channel.unary_unary(
                '/ecommerce.CustomerService/UpdateOrderStatus',
                request_serializer=ecommerce__pb2.OrderStatusRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.GetWishlist = channel.unary_unary(
                '/ecommerce.CustomerService/GetWishlist',
                request_serializer=ecommerce__pb2.SessionRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.WishlistResponse.FromString,
                _registered_method=True)
        self.AddToWishlist = channel.unary_unary(
                '/ecommerce.CustomerService/AddToWishlist',
                request_serializer=ecommerce__pb2.WishlistItemRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.RemoveFromWishlist = channel.unary_unary(
                '/ecommerce.CustomerService/RemoveFromWishlist',
                request_serializer=ecommerce__pb2.WishlistItemRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFeedback(self, request, context):
        """Legacy, kept for customer_db
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPurchasedItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=ecommerce__pb2.RegisterRequest.FromString,
                    response_serializer=ecommerce__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ecommerce__pb2.LoginRequest.FromString,
                    response_serializer=ecommerce__pb2.LoginResponse.SerializeToString,
            ),
            'SaveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveSession,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.ValidateResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'GetUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserData,
                    request_deserializer=ecommerce__pb2.UserRequest.FromString,
                    response_serializer=ecommerce__pb2.UserResponse.SerializeToString,
            ),
            'UpdateFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFeedback,
                    request_deserializer=ecommerce__pb2.FeedbackRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.CartResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=ecommerce__pb2.CartItemRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=ecommerce__pb2.CartItemRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'AddPurchasedItems': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPurchasedItems,
                    request_deserializer=ecommerce__pb2.PurchaseRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=ecommerce__pb2.PlaceOrderRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'GetBuyerOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerOrders,
                    request_deserializer=ecommerce__pb2.UserRequest.FromString,
                    response_serializer=ecommerce__pb2.OrderResponse.SerializeToString,
            ),
            'GetSellerOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerOrders,
                    request_deserializer=ecommerce__pb2.UserRequest.FromString,
                    response_serializer=ecommerce__pb2.OrderResponse.SerializeToString,
            ),
            'UpdateOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderStatus,
                    request_deserializer=ecommerce__pb2.OrderStatusRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'GetWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWishlist,
                    request_deserializer=ecommerce__pb2.SessionRequest.FromString,
                    response_serializer=ecommerce__pb2.WishlistResponse.SerializeToString,
            ),
            'AddToWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishlist,
                    request_deserializer=ecommerce__pb2.WishlistItemRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'RemoveFromWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromWishlist,
                    request_deserializer=ecommerce__pb2.WishlistItemRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/Register',
            ecommerce__pb2.RegisterRequest.SerializeToString,
            ecommerce__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/Login',
            ecommerce__pb2.LoginRequest.SerializeToString,
            ecommerce__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/SaveSession',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/ValidateSession',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/Logout',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/GetUserData',
            ecommerce__pb2.UserRequest.SerializeToString,
            ecommerce__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/UpdateFeedback',
            ecommerce__pb2.FeedbackRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/GetCart',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/AddToCart',
            ecommerce__pb2.CartItemRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/RemoveFromCart',
            ecommerce__pb2.CartItemRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/ClearCart',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/SaveCart',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPurchasedItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/AddPurchasedItems',
            ecommerce__pb2.PurchaseRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/PlaceOrder',
            ecommerce__pb2.PlaceOrderRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/GetBuyerOrders',
            ecommerce__pb2.UserRequest.SerializeToString,
            ecommerce__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/GetSellerOrders',
            ecommerce__pb2.UserRequest.SerializeToString,
            ecommerce__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/UpdateOrderStatus',
            ecommerce__pb2.OrderStatusRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/GetWishlist',
            ecommerce__pb2.SessionRequest.SerializeToString,
            ecommerce__pb2.WishlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/AddToWishlist',
            ecommerce__pb2.WishlistItemRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.CustomerService/RemoveFromWishlist',
            ecommerce__pb2.WishlistItemRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItem = channel.unary_unary(
                '/ecommerce.ProductService/RegisterItem',
                request_serializer=ecommerce__pb2.ItemRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/ecommerce.ProductService/GetItem',
                request_serializer=ecommerce__pb2.IDRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/ecommerce.ProductService/SearchItems',
                request_serializer=ecommerce__pb2.SearchRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetSellerItems = channel.unary_unary(
                '/ecommerce.ProductService/GetSellerItems',
                request_serializer=ecommerce__pb2.UserRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.UpdatePrice = channel.unary_unary(
                '/ecommerce.ProductService/UpdatePrice',
                request_serializer=ecommerce__pb2.UpdatePriceRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.UpdateQty = channel.unary_unary(
                '/ecommerce.ProductService/UpdateQty',
                request_serializer=ecommerce__pb2.UpdateQtyRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.UpdateItemFeedback = channel.unary_unary(
                '/ecommerce.ProductService/UpdateItemFeedback',
                request_serializer=ecommerce__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateSellerFeedback = channel.unary_unary(
                '/ecommerce.ProductService/UpdateSellerFeedback',
                request_serializer=ecommerce__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSellerStats = channel.unary_unary(
                '/ecommerce.ProductService/GetSellerStats',
                request_serializer=ecommerce__pb2.UserRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.RatingResponse.FromString,
                _registered_method=True)
        self.CreatePromo = channel.unary_unary(
                '/ecommerce.ProductService/CreatePromo',
                request_serializer=ecommerce__pb2.PromoRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.ResponseMsg.FromString,
                _registered_method=True)
        self.GetPromo = channel.unary_unary(
                '/ecommerce.ProductService/GetPromo',
                request_serializer=ecommerce__pb2.PromoGetRequest.SerializeToString,
                response_deserializer=ecommerce__pb2.PromoResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemFeedback(self, request, context):
        """NEW REVIEW ENDPOINTS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSellerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=ecommerce__pb2.ItemRequest.FromString,
                    response_serializer=ecommerce__pb2.ItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=ecommerce__pb2.IDRequest.FromString,
                    response_serializer=ecommerce__pb2.ItemResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=ecommerce__pb2.SearchRequest.FromString,
                    response_serializer=ecommerce__pb2.SearchResponse.SerializeToString,
            ),
            'GetSellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerItems,
                    request_deserializer=ecommerce__pb2.UserRequest.FromString,
                    response_serializer=ecommerce__pb2.SearchResponse.SerializeToString,
            ),
            'UpdatePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrice,
                    request_deserializer=ecommerce__pb2.UpdatePriceRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'UpdateQty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQty,
                    request_deserializer=ecommerce__pb2.UpdateQtyRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'UpdateItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemFeedback,
                    request_deserializer=ecommerce__pb2.FeedbackRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'UpdateSellerFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSellerFeedback,
                    request_deserializer=ecommerce__pb2.FeedbackRequest.FromString,
                    response_serializer=ecommerce__pb2.Empty.SerializeToString,
            ),
            'GetSellerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerStats,
                    request_deserializer=ecommerce__pb2.UserRequest.FromString,
                    response_serializer=ecommerce__pb2.RatingResponse.SerializeToString,
            ),
            'CreatePromo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePromo,
                    request_deserializer=ecommerce__pb2.PromoRequest.FromString,
                    response_serializer=ecommerce__pb2.ResponseMsg.SerializeToString,
            ),
            'GetPromo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromo,
                    request_deserializer=ecommerce__pb2.PromoGetRequest.FromString,
                    response_serializer=ecommerce__pb2.PromoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/RegisterItem',
            ecommerce__pb2.ItemRequest.SerializeToString,
            ecommerce__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/GetItem',
            ecommerce__pb2.IDRequest.SerializeToString,
            ecommerce__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/SearchItems',
            ecommerce__pb2.SearchRequest.SerializeToString,
            ecommerce__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/GetSellerItems',
            ecommerce__pb2.UserRequest.SerializeToString,
            ecommerce__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/UpdatePrice',
            ecommerce__pb2.UpdatePriceRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/UpdateQty',
            ecommerce__pb2.UpdateQtyRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/UpdateItemFeedback',
            ecommerce__pb2.FeedbackRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSellerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/UpdateSellerFeedback',
            ecommerce__pb2.FeedbackRequest.SerializeToString,
            ecommerce__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/GetSellerStats',
            ecommerce__pb2.UserRequest.SerializeToString,
            ecommerce__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/CreatePromo',
            ecommerce__pb2.PromoRequest.SerializeToString,
            ecommerce__pb2.ResponseMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.ProductService/GetPromo',
            ecommerce__pb2.PromoGetRequest.SerializeToString,
            ecommerce__pb2.PromoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
